@url = https://congenial-invention-wr4prj96vx93gw57-3000.app.github.dev/api/tarefas

GET {{url}}

###
POST {{url}}
Contemt-Type: application/json

{
    "id" : 10,
    "title" : "Executar Aplicação"
}

###
GET {{url}}/2